# Location of top-level MicroPython directory
MPY_DIR = /home/.../.../micropython/

# Name of module
MOD = ed25519

# Source files (.c or .py)
SRC = 	eddsa.c ed25519.h fe.c ge.c keypair.c sc.c sha512.c sign.c verify.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
ARCH = xtensawin

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
